### ISSUE TITLE
Players not rendered

### ISSUE THREAD

**Issue by Duke-Igthorn** [webbukkit/DynmapCanary#1]
Been testing around with this and it works and looks great!
(The new viewing angle on 3D maps is pretty!)
But one tiny weirdness is that apparently players are not rendered on the map.
It remains under the constant impression that 0 players are logged in and therefore shows none of them. xD

**Comment by mikeprimm** [comment]
Not seeing this: seeing player icons on both 1.1.3 and 1.2.0 version - which version and how is it configured?

**Comment by Duke-Igthorn** [comment]
Hey Hi, thanks for the superquick reply!
It happened for me on the latest 1.2.0 Canary snapshot with the latest dynmap 2.1-SNAPSHOT-2027,
hosted on a MineOS turnkey setup. I gave the instance 3GB RAM at first but later up to 6GB.
Funny enough now after a bunch of reboots, suddenly the player icons DID appear and things seem to be fine now. Pretty strange. I'll keep an eye out if the weirdness returns. :)

**Comment by mikeprimm** [comment]
OK - reopen if more to discuss
